
sample_errors <- function(model, index) {
  A <- model$output$sample[,grep("A", colnames(model$output$sample))]
  A <- matrix(A[index,], ncol = ncol(model$y))
  td <- model$xy$td
  if(td != 0) {
    xx <- model$xy$xx[-c(1:td),]
    yy <- model$xy$yy[-c(1:td),]
  } else {
    xx <- model$xy$xx
    yy <- model$xy$yy
  }
  e <- yy - xx %*% A
  e
}

#' @title Forecast with a smoothed (VAR) BETEL
#' @description Samples from the predictive distribution of the given smoothed 
#' BETEL model. Supports only VAR-type models at the time.
#'  
#' @param model Estimated model generated by \code{est_sbetel}.
#' @param NN A number of draws from the predictive distribution.
#' @param horizon Forecasting horizon.
#' @param newdata A numerical matrix containing the predictive variables. 
#' Defaults to \code{NULL} in which case the end of the data used for 
#' estimation of the model is used.
#' @param verbose Logical. If \code{TRUE} messages are produced. Defaults to \code{TRUE}. 
#' @return \code{eval_sbetel()} returns an array of the form 
#' \code{(horizon, series, draw)} consisting of the draws from the
#' predictive distribution.
#' @examples
#' cast <- forecast_sbetel(model = model, NN = 1000, horizon = 8)
#' @export
forecast_sbetel <- function(model, NN, horizon = 1, 
                            newdata = NULL, verbose = TRUE) {
  
  if(model$type != "var") stop("'forecast_sbetel() supports only var models.")
  
  #Predictors for one-step-ahead forecast
  if(is.null(newdata)) newdata <- model$y
  preds0 <- c()
  for(i in 1:model$p) {
    preds0 <- c(preds0, newdata[(nrow(newdata)-i+1),])
  }
  preds0 <- c(1, preds0)
  
  #Sampling from the predictive density
  cast <- array(NA, dim = c(horizon, ncol(model$y), NN))
  if(verbose == TRUE) cat("Sampling from the posterior predictive density... \n")
  if(verbose == TRUE) pb <- txtProgressBar(min = 0, max = NN, style = 3)
  for(j in 1:NN) {
    A_index <- sample.int(nrow(model$output$sample),1)
    A <- matrix(model$output$sample[A_index,], ncol = ncol(model$y))
    e <- sample_errors(model, A_index)
    preds <- preds0
    for(h in 1:horizon) {
      cast[h,,j] <- preds %*% A + e[sample.int(nrow(e),1),]
      preds <- c(1, cast[h,,j], preds[-c(1)])[1:length(preds)]
    }
    if(verbose == TRUE) setTxtProgressBar(pb, j)
  }
  if(verbose == TRUE) close(pb)
  cast
}
