# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_rcpp <- function(num) {
    .Call(`_sbetel_test_rcpp`, num)
}

etel_rcpp <- function(th, g, p, y, itermax, bw, lambda, td) {
    .Call(`_sbetel_etel_rcpp`, th, g, p, y, itermax, bw, lambda, td)
}

